[[language]]
name = "rust"

# On older versions of Helix, try using [language.config.check] instead
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "typescript"
auto-format = true
config = { format = { "semicolons" = "insert" } }